# Generated by Django 5.0.4 on 2024-06-06 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=30)),
                ('pdesc', models.TextField(max_length=200)),
                ('pimage', models.ImageField(upload_to='')),
            ],
        ),
    ]
