# Generated by Django 5.0.4 on 2024-06-10 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app17', '0003_geeksmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeeksModel',
        ),
        migrations.DeleteModel(
            name='UploadImage',
        ),
    ]
